### Array Manipulation

In [2]:
# Concatenate two arrays.
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [4]:
# Stack arrays vertically.
arr1=np.array([4,5,1])
arr2= np.array([13,24,10])
arr=np.vstack((arr1,arr2))
print(arr)

[[ 4  5  1]
 [13 24 10]]


In [5]:
# Stack arrays horizontally.
arr2=([[1],[2],[3]])
arr3=([[5],[6],[7]])

arr=np.hstack((arr2,arr3))
print(arr)

[[1 5]
 [2 6]
 [3 7]]


In [8]:
# Split an array into equal parts.
arr=np.arange(10)
split_arr=np.split(arr,(2))
print(split_arr)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [11]:
# Repeat elements of an array multiple times.
arr=np.arange(10)
repeat=np.repeat(arr,2)
print(repeat)

[0 0 1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8 9 9]


In [13]:
# Tile an array multiple times.

arr=np.arange(10)
array=np.tile(arr,3)
print(array)

[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]


In [15]:
# Find unique values in an array.
arr=np.array([1,2,3,44,1,2,3,6,7,8])
array=np.unique(arr)
print(array)

[ 1  2  3  6  7  8 44]


In [16]:
# Sort a 1D array.
arr=np.array([2,1,3,1,2,534,32,8923])
arr.sort()
print(arr)

[   1    1    2    2    3   32  534 8923]


In [20]:
# Sort values row-wise in a matrix. 

arr=np.random.randint(1,10,(3,3))
array=np.sort(arr,axis=1)
print(array)

[[5 6 9]
 [5 6 9]
 [3 4 5]]


In [22]:
# Sort values column-wise in a matrix
arr=np.random.randint(5,10,(3,3))
array=np.sort(arr,axis=0)
print(array)

[[5 7 5]
 [5 7 8]
 [6 9 8]]


# NumPy Array Manipulation Quick Revision

---

# 1. Concatenation

Concatenation means:
```python
joining arrays together
```

Pattern:
```python
np.concatenate((arr1, arr2))
```

Example:
```python
[1,2] + [3,4]
```

Result:
```python
[1,2,3,4]
```

---

# 2. Vertical Stacking

```python
np.vstack((arr1, arr2))
```

Meaning:
```python
stack arrays row-wise
```

Arrays are placed:
```python
top to bottom
```

---

# 3. Horizontal Stacking

```python
np.hstack((arr1, arr2))
```

Meaning:
```python
stack arrays column-wise
```

Arrays are placed:
```python
side by side
```

---

# 4. Splitting Arrays

```python
np.split(arr, parts)
```

Example:
```python
np.split(arr, 2)
```

splits array into:
```python
2 equal parts
```

Important:
```python
array size must divide equally
```

---

# 5. Repeat Elements

```python
np.repeat(arr, times)
```

Repeats:
```python
each element individually
```

Example:
```python
[1,2]
```

Result:
```python
[1,1,2,2]
```

---

# 6. Tile Arrays

```python
np.tile(arr, times)
```

Repeats:
```python
entire array pattern
```

Example:
```python
[1,2]
```

Result:
```python
[1,2,1,2]
```

---

# 7. Unique Values

```python
np.unique(arr)
```

Returns:
```python
sorted unique elements
```

Duplicates removed automatically.

---

# 8. Sorting 1D Arrays

```python
np.sort(arr)
```

Sorts values in ascending order.

---

# 9. Row-wise Sorting

```python
np.sort(arr, axis=1)
```

Each row sorted independently.

---

# 10. Column-wise Sorting

```python
np.sort(arr, axis=0)
```

Each column sorted independently.

---

# 11. Important Axis Reminder

```python
axis=0 -> column direction
axis=1 -> row direction
```

---

# 12. Important Mental Models

## concatenate()
```python
join arrays
```

---

## stack()
```python
increase dimensions
```

---

## repeat()
```python
repeat elements
```

---

## tile()
```python
repeat patterns
```

---

# 13. Biggest Beginner Mistakes

## Mistake 1
Confusing:
```python
repeat()
```

with:
```python
tile()
```

### repeat()
duplicates elements.

### tile()
duplicates array pattern.

---

## Mistake 2
Confusing:
```python
concatenate()
```

with:
```python
stack()
```

Stacking usually adds structural dimension organization.

---

## Mistake 3
Forgetting axis meaning during sorting.

---

# 14. AIML Importance

These operations are heavily used in:
- dataset construction
- batching
- tensor reshaping
- augmentation
- preprocessing
- feature engineering

Especially:
```python
concatenate
stack
split
```

are everywhere in ML pipelines.