# Axis Operations

In [1]:
import numpy as np

In [7]:
# Find the row-wise sum of a matrix.
arr=np.arange(9).reshape(3,3)
print(arr)
sum_arr=np.sum(arr,axis=1)
print(sum_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 3 12 21]


In [8]:
# Find the column-wise sum of a matrix.
arr=np.arange(9).reshape(3,3)
print(arr)
col_sum=np.sum(arr,axis=0)
print(col_sum)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 9 12 15]


In [9]:
# Calculate the row-wise mean.
arr=np.arange(9).reshape(3,3)
print(arr)
mean_arr=np.mean(arr,axis=1)
print(mean_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1. 4. 7.]


In [10]:
# Calculate the column-wise mean.
arr=np.arange(9).reshape(3,3)
print(arr)
col_mean=np.mean(arr,axis=0)
print(col_mean)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[3. 4. 5.]


In [11]:
# Find the maximum value in each row.
arr=np.arange(9).reshape(3,3)
print(arr)
max_row=np.max(arr,axis=1)
print(max_row)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[2 5 8]


In [13]:
# Find the minimum value in each column.
arr=np.arange(9).reshape(3,3)
print(arr)
min_col=np.min(arr,axis=0)
print(min_col)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


In [14]:
# Find the index of the maximum value in an array.
arr=np.arange(9).reshape(3,3)
print(arr)
value=np.max(arr)
print(value)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
8


In [15]:
# Find the index of the minimum value in an array.
arr=np.arange(9).reshape(3,3)
print(arr)
value=np.min(arr)
print(value)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
0


In [16]:
# Calculate the cumulative sum of array elements.

arr=np.arange(9).reshape(3,3)
print(arr)
value=np.cumsum(arr)
print(value)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 0  1  3  6 10 15 21 28 36]


In [18]:
# Calculate the cumulative product of array elements.
arr=np.arange(1,10).reshape(3,3)
print(arr)
value=np.cumprod(arr)
print(value)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[     1      2      6     24    120    720   5040  40320 362880]


# NumPy Axis Operations Quick Revision

---

# 1. What is Axis?

Axis means:
```python
direction along which operation happens
```

For 2D arrays:

```python
axis 0 -> vertical direction (rows)
axis 1 -> horizontal direction (columns)
```

---

# 2. Important Mental Model

For shape:
```python
(rows, columns)
```

Example:
```python
(3,4)
```

Means:
- 3 rows
- 4 columns

---

# 3. Axis 0 Operations

```python
axis=0
```

Operation happens:
```python
down the rows
```

Result:
```python
column-wise result
```

Example:
```python
np.sum(arr, axis=0)
```

Adds column values.

---

# 4. Axis 1 Operations

```python
axis=1
```

Operation happens:
```python
across columns
```

Result:
```python
row-wise result
```

Example:
```python
np.sum(arr, axis=1)
```

Adds row values.

---

# 5. Row-wise Sum

```python
np.sum(arr, axis=1)
```

---

# 6. Column-wise Sum

```python
np.sum(arr, axis=0)
```

---

# 7. Row-wise Mean

```python
np.mean(arr, axis=1)
```

---

# 8. Column-wise Mean

```python
np.mean(arr, axis=0)
```

---

# 9. Maximum Values

## Row-wise Maximum
```python
np.max(arr, axis=1)
```

## Column-wise Maximum
```python
np.max(arr, axis=0)
```

---

# 10. Minimum Values

## Row-wise Minimum
```python
np.min(arr, axis=1)
```

## Column-wise Minimum
```python
np.min(arr, axis=0)
```

---

# 11. Index of Maximum Value

```python
np.argmax(arr)
```

Returns:
```python
index of largest element
```

---

# 12. Index of Minimum Value

```python
np.argmin(arr)
```

Returns:
```python
index of smallest element
```

---

# 13. Cumulative Sum

```python
np.cumsum(arr)
```

Example:
```python
[1,2,3,4]
```

Result:
```python
[1,3,6,10]
```

Because:
```python
1
1+2
1+2+3
1+2+3+4
```

---

# 14. Cumulative Product

```python
np.cumprod(arr)
```

Example:
```python
[1,2,3,4]
```

Result:
```python
[1,2,6,24]
```

---

# 15. Important Interview Insight

```python
argmax()
```

returns:
```python
index
```

NOT the actual maximum value.

Same for:
```python
argmin()
```

---

# 16. Biggest Beginner Mistakes

## Mistake 1
Confusing:
```python
axis=0
axis=1
```

Remember:
```python
axis 0 -> vertical
axis 1 -> horizontal
```

---

## Mistake 2
Thinking:
```python
argmax()
```

returns value instead of position.

---

## Mistake 3
Ignoring cumulative operations.

Very important in:
- probability
- finance
- sequential computations

---

# 17. AIML Importance

Axis operations are everywhere in:
- normalization
- feature statistics
- batch processing
- neural network tensors
- image processing
- data aggregation

Understanding axes properly is mandatory for deep learning.