# Boolean Logic and Conditions 


In [1]:
import numpy as np

In [3]:
# Extract all even numbers from an array.
arr=np.arange(10)
even= arr[arr%2==0]
print(even)

[0 2 4 6 8]


In [4]:
# Extract all odd numbers from an array.
arr=np.arange(10)
odd= arr[arr%2!=0]
print(odd)

[1 3 5 7 9]


In [6]:
# Replace all negative values with zero.
arr=np.arange(-5,10)
arr[arr<0]=0
print(arr)

[0 0 0 0 0 0 1 2 3 4 5 6 7 8 9]


In [10]:
# Replace all values greater than 100 with a fixed number.
fixed_no=int(input())
arr=np.random.randint(99,110,(3,3))
arr[arr>100]=fixed_no
print(arr)

[[  4 100   4]
 [  4   4   4]
 [ 99   4 100]]


In [15]:
# Use where() to apply conditional logic.
arr=np.random.randint(50,100,(3,3))
array=np.where(arr>55,1,0)
print(arr)
print(array)

[[85 88 72]
 [95 78 86]
 [51 91 62]]
[[1 1 1]
 [1 1 1]
 [0 1 1]]


In [16]:
# Apply multiple conditions together on an array.
arr=np.random.randint(50,100,(3,3))
filtered = arr[(arr > 60) & (arr < 90)]
print(arr)
print(filtered)

[[68 74 86]
 [95 58 51]
 [84 77 78]]
[68 74 86 84 77 78]


In [17]:
# Detect missing values in an array.
arr = np.array([1, 2, np.nan, 4, np.nan])
missing = np.isnan(arr)
print(missing)

[False False  True False  True]


In [19]:
# Remove missing values from an array.
arr = np.array([1, 2, np.nan, 4, np.nan, 6])
new_arr = arr[~np.isnan(arr)]
print(new_arr)

[1. 2. 4. 6.]


In [20]:
# Replace missing values with a custom value.
arr = np.array([1, 2, np.nan, 4, np.nan])
arr[np.isnan(arr)] = 0
print(arr)

[1. 2. 0. 4. 0.]


In [21]:
# Count how many elements satisfy a condition.
arr = np.array([10, 25, 30, 45, 50])
count = np.sum(arr > 30)
print(count)

2


# NumPy Boolean Logic & Conditions Quick Revision

---

# 1. What is Boolean Indexing?

Boolean indexing means:
```python
filtering data using True/False conditions
```

Example:
```python
arr[arr > 5]
```

Condition creates:
```python
True / False mask
```

NumPy keeps only `True` positions.

---

# 2. Core Filtering Pattern

```python
arr[condition]
```

Example:
```python
arr[arr % 2 == 0]
```

Gets even numbers.

---

# 3. Even Numbers

Condition:
```python
arr % 2 == 0
```

Reason:
```python
even numbers leave remainder 0
```

---

# 4. Odd Numbers

Condition:
```python
arr % 2 != 0
```

or:
```python
arr % 2 == 1
```

---

# 5. Replace Values Using Conditions

Example:
```python
arr[arr < 0] = 0
```

Meaning:
```python
replace negative values with 0
```

---

# 6. np.where()

Structure:
```python
np.where(condition, true_value, false_value)
```

Example:
```python
np.where(arr > 5, 1, 0)
```

Meaning:
- if condition true → 1
- else → 0

---

# 7. Multiple Conditions

Use:
```python
&
|
```

NOT:
```python
and
or
```

Example:
```python
(arr > 2) & (arr < 10)
```

---

# 8. Important Rule

Wrap each condition in parentheses.

Correct:
```python
(arr > 2) & (arr < 10)
```

Wrong:
```python
arr > 2 & arr < 10
```

---

# 9. Missing Values in NumPy

Missing values are usually:
```python
np.nan
```

Meaning:
```python
Not a Number
```

---

# 10. Detect Missing Values

```python
np.isnan(arr)
```

Returns:
```python
True where value is missing
```

---

# 11. Remove Missing Values

Use boolean filtering:

```python
arr[~np.isnan(arr)]
```

Important:
```python
~
```

means:
```python
logical NOT
```

---

# 12. Replace Missing Values

Example:
```python
arr[np.isnan(arr)] = 0
```

Replaces NaN with 0.

---

# 13. Count Condition Matches

Example:
```python
np.sum(arr > 5)
```

Reason:
```python
True = 1
False = 0
```

So summing counts True values.

---

# 14. Important Mental Models

## Boolean Mask
```python
[True False True]
```

Controls selection.

---

## Vectorized Conditions
Conditions apply to entire arrays simultaneously.

No loops needed.

---

# 15. Biggest Beginner Mistakes

## Mistake 1
Using:
```python
and / or
```

instead of:
```python
& / |
```

---

## Mistake 2
Forgetting parentheses around conditions.

---

## Mistake 3
Confusing:
```python
np.where()
```

with filtering.

`where()` performs conditional replacement/transformation.

---

## Mistake 4
Not understanding:
```python
~np.isnan(arr)
```

`~` reverses True/False values.

---

# 16. AIML Importance

Boolean operations are used everywhere:
- data cleaning
- outlier removal
- preprocessing
- feature filtering
- thresholding predictions
- handling missing values

This section is extremely important for real ML pipelines.