# DATA TYPES

In [11]:
# Check the datatype of an array.
import numpy as np
arr=np.arange(10)
print(arr.dtype)

int64


In [12]:
#Convert an integer array into float datatype.
arr = np.arange(10)
float_arr = arr.astype(float)
print(float_arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [13]:
# Convert a float array into integer datatype.
arr=np.arange(10,dtype=float)
new=arr.astype(int)
print(new.dtype)



int64


In [14]:
# Convert numeric values into string datatype.
arr = np.array([1, 2, 3, 4, 5])
str_arr = arr.astype(str)
print(str_arr)
print(str_arr.dtype)

['1' '2' '3' '4' '5']
<U21


In [15]:
# Observe datatype behavior when integers and floats are mixed together.

arr=np.array([1,2.3,4,5,7.8])
print(arr)
print(arr.dtype)

[1.  2.3 4.  5.  7.8]
float64


# NumPy Data Types Quick Revision

---

# 1. What is dtype?

`dtype` means:
> datatype of elements stored inside a NumPy array.

Unlike Python lists,
NumPy arrays store homogeneous data.

Meaning:
```python
same datatype for all elements
```

This is one reason NumPy is fast.

---

# 2. Check Datatype

```python
arr.dtype
```

Example:
```python
import numpy as np

arr = np.array([1,2,3])

print(arr.dtype)
```

Output:
```python
int64
```

---

# 3. Common NumPy Datatypes

| Datatype | Meaning |
|---|---|
| int32 / int64 | Integer |
| float32 / float64 | Decimal numbers |
| bool | True/False |
| str / <U | String datatype |

---

# 4. Type Conversion

Use:
```python
astype()
```

Structure:
```python
arr.astype(new_datatype)
```

---

# 5. Convert Integer → Float

```python
arr.astype(float)
```

Example:
```python
[1,2,3]
```

Becomes:
```python
[1. 2. 3.]
```

---

# 6. Convert Float → Integer

```python
arr.astype(int)
```

Important:
```python
decimal part gets removed
```

Example:
```python
[1.9, 2.8]
```

Becomes:
```python
[1,2]
```

NOT rounded.

---

# 7. Convert Numeric → String

```python
arr.astype(str)
```

Example:
```python
[1,2,3]
```

Becomes:
```python
['1' '2' '3']
```

---

# 8. Mixed Datatypes Behavior

Example:
```python
np.array([1, 2.5, 3])
```

Output dtype:
```python
float64
```

Why?

NumPy upgrades datatype automatically.

This is called:
```python
upcasting
```

---

# 9. Datatype Priority

General hierarchy:

```python
bool → int → float → string
```

NumPy chooses the safer/larger datatype.

---

# 10. Important AIML Insight

Datatype affects:
- memory usage
- computation speed
- model performance
- GPU efficiency

Example:
```python
float32
```

is heavily used in deep learning.

---

# 11. Biggest Beginner Mistakes

## Mistake 1
Thinking arrays can freely mix types like Python lists.

Wrong.

NumPy tries to force one datatype.

---

## Mistake 2
Expecting float → int conversion to round values.

It truncates decimals.

---

## Mistake 3
Forgetting astype() returns a new array.

```python
new_arr = arr.astype(float)
```

Original array remains unchanged.