### Indexing and Slicing 


In [22]:
# Access the first element of an array.
import numpy as np 
arr=([1,2,3,1,2,34,5,9])
arr[0]

1

In [23]:
# Access the last element of an array.
arr=np.arange(10)
print(arr[-1])

9


In [24]:
# Slice the first five elements from an array.
arr=np.arange(10)
sliced_arr=arr[0:6]
print(sliced_arr)

[0 1 2 3 4 5]


In [25]:
# Reverse an array using slicing.
arr=np.arange(10)
rev=arr[::-1]
print(rev)

[9 8 7 6 5 4 3 2 1 0]


In [26]:
#Extract a specific row from a matrix.

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

row=arr[1]
print(row)

[4 5 6]


In [27]:

# Extract a specific column from a matrix.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

col=arr[:,0]
print(col)

[1 4 7]


In [28]:
# Extract a submatrix from a larger matrix.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
sub= arr[1:,0:2]
print(sub)

[[4 5]
 [7 8]]


In [29]:
# Use boolean indexing to filter values. 
arr=np.arange(10)
val=arr[arr>5]
print(val)

[6 7 8 9]


In [30]:
# Use fancy indexing with index arrays.
# Fancy indexing is a NumPy technique where you use arrays or lists of indexes to select multiple specific elements at once.
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

elements = arr[[0,1,2], [2,0,1]]
print(elements)

[3 4 8]


In [31]:
# Filter values based on a condition.
arr = np.array([2, 5, 8, 1, 10])

filtered = arr[arr > 5]

print(filtered)

[ 8 10]


# NumPy Indexing & Slicing Quick Revision

---

# 1. Basic Indexing

## Access First Element
```python
arr[0]
```

## Access Last Element
```python
arr[-1]
```

Negative indexing starts from the end.

---

# 2. 2D Array Indexing

Structure:
```python
array[row, column]
```

Example:
```python
arr[1,2]
```

Means:
- second row
- third column

---

# 3. Slicing Syntax

Structure:
```python
[start : stop : step]
```

Important:
```python
stop is excluded
```

---

# 4. Common Slicing Patterns

## First 5 Elements
```python
arr[:5]
```

## Reverse Array
```python
arr[::-1]
```

## Every Second Element
```python
arr[::2]
```

---

# 5. Row Extraction

## Specific Row
```python
arr[1]
```

or

```python
arr[1,:]
```

---

# 6. Column Extraction

## Specific Column
```python
arr[:,1]
```

Meaning:
- all rows
- second column

---

# 7. Submatrix Extraction

Example:
```python
arr[0:2, 1:3]
```

Means:
- rows 0 to 1
- columns 1 to 2

---

# 8. Boolean Indexing

Condition creates True/False mask.

Example:
```python
arr[arr > 5]
```

Keeps only values greater than 5.

---

# 9. Fancy Indexing

Use index arrays.

Example:
```python
arr[[0,2,4]]
```

Gets:
- index 0
- index 2
- index 4

---

# 10. Most Important Mental Models

## Indexing
Gets specific positions.

## Slicing
Gets ranges.

## Boolean Indexing
Gets values matching conditions.

## Fancy Indexing
Gets multiple custom positions.

---

# Golden Rules

```python
axis 0 -> rows
axis 1 -> columns
```

```python
: means “everything”
```

```python
negative index -> from end
```

```python
step = -1 -> reverse
```

---

# AIML Connection

These operations are used constantly in:
- dataset filtering
- train/test splitting
- feature selection
- image processing
- tensor manipulation
- preprocessing pipelines

If slicing feels slow mentally,
you are not ready for advanced NumPy yet.