# Basic Operations

In [19]:
# Add two arrays element-wise.
import numpy as np
arr1=np.arange(4)
arr2=np.arange(4,8)
print(arr1+arr2)

[ 4  6  8 10]


In [20]:
# Subtract one array from another.
arr1=np.arange(4)
arr2=np.arange(4,8)
print(arr2-arr1)

[4 4 4 4]


In [21]:
# Multiply two arrays element-wise.
arr1=np.arange(4)
arr2=np.arange(4,8)
print(arr1*arr2)

[ 0  5 12 21]


In [22]:
# Divide two arrays element-wise.
arr1=np.arange(4)
arr2=np.arange(4,8)
print(arr1/arr2)


[0.         0.2        0.33333333 0.42857143]


In [23]:
# Find the square of each element.
arr1=np.arange(4)
print(arr1**2)

[0 1 4 9]


In [24]:
# Find the cube of each element.
arr1=np.arange(4)
print(arr1**3)

[ 0  1  8 27]


In [25]:
# Calculate square roots of array values.
arr1=np.arange(4)
print(np.sqrt(arr1))

[0.         1.         1.41421356 1.73205081]


In [26]:
# Apply exponential function to array values.

arr = np.arange(4)
print(np.exp(arr))

[ 1.          2.71828183  7.3890561  20.08553692]


In [27]:
# Apply logarithm function to array values.

arr = np.arange(1,5)
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436]


In [28]:
# Find absolute values of negative numbers.
arr=np.arange(-10,-1)
print(np.abs(arr))


[10  9  8  7  6  5  4  3  2]


# NumPy Basic Operations Quick Revision

---

# 1. Vectorized Operations

NumPy performs operations:
```python
element-wise
```

Meaning:
same index interacts with same index.

Example:
```python
[1,2,3] + [4,5,6]
```

Result:
```python
[5,7,9]
```

No loops needed.

---

# 2. Element-wise Addition

```python
arr1 + arr2
```

Example:
```python
[1,2] + [3,4]
```

Result:
```python
[4,6]
```

---

# 3. Element-wise Subtraction

```python
arr1 - arr2
```

Example:
```python
[5,7] - [2,3]
```

Result:
```python
[3,4]
```

---

# 4. Element-wise Multiplication

```python
arr1 * arr2
```

Important:
```python
* is NOT matrix multiplication
```

Example:
```python
[2,3] * [4,5]
```

Result:
```python
[8,15]
```

---

# 5. Element-wise Division

```python
arr1 / arr2
```

Example:
```python
[10,20] / [2,5]
```

Result:
```python
[5.,4.]
```

Output becomes float.

---

# 6. Square of Elements

```python
arr ** 2
```

Example:
```python
[1,2,3]
```

Result:
```python
[1,4,9]
```

---

# 7. Cube of Elements

```python
arr ** 3
```

---

# 8. Square Root

```python
np.sqrt(arr)
```

Example:
```python
[1,4,9]
```

Result:
```python
[1.,2.,3.]
```

---

# 9. Exponential Function

```python
np.exp(arr)
```

Calculates:
```python
e^x
```

Example:
```python
e^1, e^2, e^3
```

---

# 10. Logarithm Function

```python
np.log(arr)
```

Calculates:
```python
natural logarithm (ln)
```

Important:
```python
log(0) is undefined
```

---

# 11. Absolute Values

```python
np.abs(arr)
```

Converts negatives into positive values.

Example:
```python
[-2,-5,3]
```

Result:
```python
[2,5,3]
```

---

# 12. Important Mental Model

NumPy operations are:
```python
vectorized
```

Meaning:
operations happen on entire arrays simultaneously.

This is why NumPy is fast.

---

# 13. Biggest Beginner Mistakes

## Mistake 1
Thinking:
```python
*
```

does matrix multiplication.

Wrong.

Use:
```python
@
```

or:
```python
np.dot()
```

for matrix multiplication.

---

## Mistake 2
Using loops unnecessarily.

Bad NumPy practice.

---

## Mistake 3
Forgetting operations are element-wise.

Always think:
```python
same index interacts with same index
```

---

# 14. AIML Connection

These operations are used constantly in:
- normalization
- feature scaling
- activations
- tensor math
- neural networks
- statistical calculations