# LEVEL 1 — Foundations (1–50)

In [1]:
import numpy as np

In [2]:
# Create a 1D array from a list

one_dim=np.array([1,2,3])
print(one_dim)

[1 2 3]


In [6]:
# Create a 2D array
two_dim=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two_dim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# Create a 3×3 matrix filled entirely with zeros.
zeros=np.zeros((3,3))
print(zeros)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# Create a 5×5 matrix filled entirely with ones.

one=np.ones((5,5))
print(one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
# Create a 4×4 identity matrix.

mat=np.eye(4)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Create a diagonal matrix using custom diagonal values. 
arr=np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [15]:
# Generate numbers from 0 to 20 using 
arr=np.arange(21)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [17]:
# Generate evenly spaced decimal values between two numbers using
space=np.linspace(0,1,5)
print(space)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Generate random integers within a specific range.
